<?php
$config = [
	'Datasources' => [
		'default' => [
			'className' => 'Cake\Database\Connection',
			'driver' => 'Cake\Database\Driver\MySQL',
			'persistent' => false,
			'host' => 'localhost',
			'login' => 'root',
			'password' => '',
			'database' => 'quickappscms2',
			'prefix' => false,
			'encoding' => 'utf8',
			'log' => true,
		],
	],
	'Security' => [
		'salt' => '__SALT__',
	],
	'debug' => 2,
];
