<?php
Configure::write('coreModules',
    array(
        'Field',
        'Block',
        'Menu',
        'Node',
        'System',
        'Taxonomy',
        'User',
        'Locale',
        'Comment'
    )
);